# Basic Settings
title: Your Site's Title
description: A description of your site
baseurl: ""
url: "https://markhughesqa.com"
permalink: /:title

# Build Settings
markdown: kramdown
theme: minima

google_analytics: G-CHK0QPMQXC